### PR TITLE
Fix for #6153 Allow MongoDB cursor streaming via each()

### PR DESCRIPTION
**Pull request by klimov-paul**
Fix for https://github.com/yiisoft/yii2/issues/6153 Allow MongoDB cursor streaming via each()

### CODE REVIEW

**Comment by klimov-paul** [comment]
Note: this enhancement breaks the BC cahnging the signature of `Query` methods.

**Comment by cebe** [comment]
can you explain why removing indexBy is necessary?

**Comment by klimov-paul** [comment]
It is not necessary - it is an optimization. I can revert it, but there is still matter around `buildCursor`, which visibility has changed.

**Comment by cebe** [comment]
I see.

**Comment by klimov-paul** [comment]
Migrated to #12

**Pull request closed without merging**
