### PR TITLE
Fix #56 new MongDB driver

### LINKED ISSUE #56: New MongoDB driver
Hi guys.
Are you planning in the near future migrate to new [MongoDB driver for PHP](http://docs.php.net/manual/en/set.mongodb.php). As mentioned [here](https://www.mongodb.com/blog/post/call-feedback-new-php-and-hhvm-drivers) next-generation driver will support PHP 5.x, HHVM, and PHP 7.0. Since new PHP release is very close, some of us would be happy to have ability to use MongoDB with new 7.0 version or HHVM as well.

Thanks

### PR DESCRIPTION
**Pull request by klimov-paul**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #56, #76, #33

### CODE REVIEW

**Comment by klimov-paul** [comment]
No GridFS implementation provided yet.

**Comment by klimov-paul** [comment]
Fixes #76 as well

**Comment by klimov-paul** [comment]
Travis buld successful.

**Comment by klimov-paul** [comment]
Fixes #33 as well

**Comment by Sammaye** [comment]
Interesting, so this bypasses the PHPLib and goes straight to the driver?

**Comment by klimov-paul** [comment]
> this bypasses the PHPLib and goes straight to the driver?

Yes. In this way extension is much more clear, allowing to resolve several issues.

**Comment by Sammaye** [comment]
Sweet I like it

**Comment by klimov-paul** [comment]
Merged
Will provide GridFS separately, see #117

**Pull request merged**
