### PR TITLE
Fixed generation wrong condition fo NOT IN query

### PR DESCRIPTION
**Pull request by webdevsega**

### CODE REVIEW

**Comment by samdark** [comment]
@cebe could you check/merge it?

**Comment by cebe** [comment]
Looks good to me, however we may instead use `!=` operator?

**Comment by cebe** [comment]
related to #37

**Comment by webdevsega** [comment]
@cebe This condition is true only for one case. So I think my code looks clearer.

**Comment by cebe** [comment]
We added #37 for performance reasons, so why don't these count for the "not in" case?

**Comment by cebe** [comment]
I'm fine with merging it this way but I'd like to understand the reasoning behind it.

**Comment by samdark** [comment]
@webdevsega ?

**Comment by webdevsega** [comment]
The condition {'$nin' => [test_value]} is equivalent to {'$ne' => test_value}. MongoDB query planner converts them to the same conditions. In this case, we need to make a performance test using '$ne' instead '$nin'.
In #37 each relation hasOne generated unnecessary condition '$in'.

**Comment by cebe** [comment]
Thanks!

**Pull request merged**
