### PR TITLE
Upgrade for new Driver

### PR DESCRIPTION
**Pull request by Sammaye**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | no
| Fixed issues  | https://github.com/yiisoft/yii2-mongodb/issues/56

### CODE REVIEW

**Comment by tuyakhov** [comment]
Those changes will affect backward compatibility. A lot of developers would complain.

**Comment by Sammaye** [comment]
Which change concerns you?

These are the BC parts I see as effecting:

- No text search command (should be operator now)
- aggregate now uses a different signature

And that's about it atm

**Comment by Sammaye** [comment]
The other one I can think of is that the connection has changed how to set the default database differently. That is still very much a sort of RFC though and I doubt such a thing will be in the ext 2.1 branch

**Comment by tuyakhov** [comment]
Yes. I agree. Probably we should not care about backward compatibility at all. Good job.

**Comment by Sammaye** [comment]
It is very difficult to be BC since the driver is such a massive, fundamental change there is no way to get 100% BC, but if you find something that could cause problems let me know :)

**Comment by Sammaye** [comment]
I believe this code is currently suffering a PHP bug which throws a random recursion error for find function logging only http://stackoverflow.com/questions/37456845/what-does-json-error-recursion-mean-from-json-encode all other functions work

**Comment by Sammaye** [comment]
It seems my latest commit may have fixed it, got to do more testing

**Comment by klimov-paul** [comment]
Closed in favor to #116

**Pull request closed without merging**
