### PR TITLE
* ActiveRecord: fix for toArray serialization;

### PR DESCRIPTION
**Pull request by rowdyroad**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Fix toArray serialization for ActiveRecord.

### CODE REVIEW

**Comment by klimov-paul** [comment]
Change is incorrect: in this way you eliminate aboility of usage `ObjectID` instance from returned array.

**Comment by rowdyroad** [comment]
Without this fix BaseActiveRecord::toArray return an empty array for ObjectID

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/issues/5624

**Comment by klimov-paul** [comment]
332edb1fa03255a1188c174e30042bbac964a4ee

**Pull request closed without merging**
