### PR TITLE
Probably a typo

### PR DESCRIPTION
**Pull request by loglinn05**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

### CODE REVIEW

**Comment by bizley** [comment]
Hm, yes, it looks like it was copied from the example above it. Could you correct it as well in other language versions?

**Comment by loglinn05** [comment]
> Hm, yes, it looks like it was copied from the example above it. Could you correct it as well in other language versions?

I just did it in English and Japanese language versions. As far as I could see, there is no such an article in the French one.

**Comment by bizley** [comment]
Please add all here in single PR, just push more to the same branch.

**Comment by loglinn05** [comment]
> Please add all here in single PR, just push more to the same branch.

OK. I'll do it this way next time.

**Comment by bizley** [comment]
Ehm, why not this time? 😕

**Comment by loglinn05** [comment]
I did it already. Best wishes!
https://github.com/yiisoft/yii2-mongodb/pull/341

**Comment by loglinn05** [comment]
And I'm very sorry for creating so many pull requests. I'm just learning.

**Comment by bizley** [comment]
Great, thanks! Not a problem, don't worry.

**Pull request closed without merging**
