### PR TITLE
Each start key fix

### PR DESCRIPTION
**Pull request by ziaratban**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

start index in each() method is `1`.
now start from `0`.

### CODE REVIEW

**Comment by rustamwin** [comment]
Duplicate of #291

**Comment by ziaratban** [comment]
> 
> 
> Duplicate of #291

Not Duplicate. 
`better performance for exists() method of Query class` exists in master branch.

how i can remove this commit(of master branch) from another branch ?

**Comment by samdark** [comment]
@ziaratban by rebasing.

**Comment by samdark** [comment]
Could likely cause issues with current code in case it relies on indexes. Should be released in 2.2.

**Comment by samdark** [comment]
@ziaratban would you please add a line for CHANGELOG.md?

**Pull request merged**
