### PR TITLE
Fixed #136: getChildRoles() throws an exception when role has no children

### LINKED ISSUE #136: yii\mongodb\Collection::findOne() return false
### What steps will reproduce the problem?

```php
User::getCollection()->findOne(['some_field' => 'not_find_value']);
```

### What's expected?

`array` or `null`

### What do you get instead?

`false`
Be cause function `current([]);` in method `yii\mongodb\Collection::findOne()` return `false`

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.8
| Yii MongoDB version    | 2.1.0
| MongoDB server version | 3.2
| PHP version            | 5.6
| Operating system       | Win

### PR DESCRIPTION
**Pull request by MysteryDragon**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #161

### CODE REVIEW

**Comment by MysteryDragon** [comment]
There are no fixes between versions...

**Comment by MysteryDragon** [comment]
@samdark , I updated commit (if you still insist on this).

**Comment by samdark** [comment]
Not really...

**Comment by MysteryDragon** [comment]
@samdark , I can change it back :)

**Comment by MysteryDragon** [comment]
... Done.)

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
